### PR TITLE
fix: use the correct args

### PR DESCRIPTION
**Pull request by TonybynMp4**
## Checklist

- [ ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

### CODE REVIEW

**Comment by DevX32** [comment]
@TonybynMp4 if we drink any alcohol or drink stuff why should it update the hunger and same as food if we eat then why thirst

**Comment by TonybynMp4** [comment]
> @TonybynMp4 if we drink any alcohol or drink stuff why should it update the hunger and same as food if we eat then why thirst

Because that's how it is.

**Comment by DevX32** [comment]
> > @TonybynMp4 if we drink any alcohol or drink stuff why should it update the hunger and same as food if we eat then why thirst
> 
> Because that's how it is.

isnt that opposite

**Comment by TonybynMp4** [comment]
> isnt that opposite

The event takes hunger & thirst as args, you NEED to pass it the current values / new values, it's just how it works.
And yes when you drink alcohol you get ***less thirsty***, you should try it one day.

**Review by mafewtm — APPROVED** [review]

**Pull request merged**
