### PR TITLE
refactor(client): Improve binoculars loop

### PR DESCRIPTION
**Pull request by ihyajb**
**Describe Pull request**
Removed a loop that was always running to check if a player was actively using binoculars. 
I also removed random code that would make non-freemode peds speak when looking into the binoculars. 
I also added a small, 1 second camera movement when leaving the binoculars.

However still needs a bit of testing, so marking as draft for now

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality?
**Kinda**
- Does your code fit the style guidelines?
**Yes**
- Does your PR fit the contribution guidelines?
**Yes**

### CODE REVIEW

**Comment by ihyajb** [comment]
Also ill wait until #4 gets merged, might be some conflicts so id rather just fix them after on my branch

**Comment by ChatDisabled** [comment]
@ihyajb all good now?

**Comment by ihyajb** [comment]
I think there was 1 last thing i had to push, i'm not home so i'll do it tomorrow

**Comment by ihyajb** [comment]
Linting fixed, good to merge after review 👍🏼

**Pull request merged**
