### PR TITLE
refactor: fix: ! Split smallresources into subprojects

### PR DESCRIPTION
**Pull request by artur-michalak**
## Description

Reading [this issue](https://github.com/Qbox-project/qbx_smallresources/issues/43) I decided to do something.
In addition to the breakdown, I improved the scripts, including vehicles pushing, seat shuffe and teleports.

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

BREAKING CHANGE:
The project has been partially broken up.

### CODE REVIEW

**Comment by artur-michalak** [comment]
outdated
```yaml
  - action: download_github
    dest: ./resources/[qbx]/[qbx_smallresources]
    ref: main
    src: https://github.com/qbox-project/qbx_smallresources
```

**Comment by Manason** [comment]
Thanks for helping out with this. I like some of the splits like qbx_vehiclepush. Others, I feel are so trivial that it isn't worth the overhead of the team maintaining a resource. While I'm not sure what to do with them, if there is just a small snippet to basically call a native, I think it's fine for it to live in small resources for now, unless we have a really great split to put it in.

One option is to have a repository that is a collection of snippets, but isn't itself a resource. That would be a place where people can just upload snippets to do different things and server owners can copy and paste where they feel is best.

Another option is to keep small resources, but only include these small snippets, whereas anything of moderate size/complexity gets split out.

In any case, the strategy we've been using up until now has been to split when and where it makes sense and chip away at small resources. Maybe the smaller it gets the clearer the answer for what to do with the rest will become. That is to say, I think the best way forward with this PR is to agree on the most obvious splits, and do those first.

**Comment by artur-michalak** [comment]
I agree with you. I made these splits to see what was worth tearing off.  Keeping such scripts in smallresources separate modules and removal by server owners would also be good option.

**Comment by artur-michalak** [comment]
I like such a breakdown, what do you think about it?

**Review by Manason — APPROVED** [review]
I'm not yet sure that all of these should be split into a separate repo/resource, but I think this is definitely an improvement so fine to merge this.

**Pull request merged**
