### PR TITLE
Hide hud components

### PR DESCRIPTION
**Pull request by AfterLifeStudio**
there is no need to use the hidehudcomponentthisframe native every frame you can just change the size of the component to zero and reset it when you want to show the component and also you dont need displayammothisframe because the first native we are using also do same job

### CODE REVIEW

**Review by Manason — APPROVED** [review]
Could this cause incompatibility issues with natives that would rely on the hud component existing? Possibly https://docs.fivem.net/natives/?_0xBC4C9EA5391ECC0D?

**Comment by AfterLifeStudio** [comment]
hey guys can you approve this

**Comment by mafewtm** [comment]
Manason's question was never answered. We need to know if these will now still be active or not. All this seems to do is set the size to 0, not disable them.

**Comment by AfterLifeStudio** [comment]
> Manason's question was never answered. We need to know if these will now still be active or not. All this seems to do is set the size to 0, not disable them.

sorry for not replying in the pr but i did inform him about this in the voice channel that even the hidehudcomponent only hides it but does not disable it so technically its still showing the ui but the native is hiding it
so its all good for this pr you can ask manason

**Review by mafewtm — APPROVED** [review]

**Pull request merged**
