### PR TITLE
add drawtext to locales

### PR DESCRIPTION
**Pull request by bicatcho11**
## Description

add drawtext to locales

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

### CODE REVIEW

**Review by mafewtm — APPROVED** [review]

**Review by TonybynMp4 — APPROVED** [review]

**Comment by bicatcho11** [comment]
why ?

**Comment by BerkieBb** [comment]
> why ?

This is the same way qbx_ambulancejob failed to load, because of using locales in the config. It gave me an error that there was a circular dependency.

**Comment by bicatcho11** [comment]
> > why ?
> 
> This is the same way qbx_ambulancejob failed to load, because of using locales in the config. It gave me an error that there was a circular dependency.

**Comment by bicatcho11** [comment]
@BerkieBb

**Pull request merged**
