### PR TITLE
New Consumable Logic

### PR DESCRIPTION
**Pull request by SOH69**
This PR changes on how the consumable works, its a very messy thing to work and people ingenerally make a mess within code while doing it.
This wrapper will improve the efficiency of consumables, remove all possible glitches and help devs to add item easily to consumables
The consumables.md potrays how to add items and all the feautures

### CODE REVIEW

**Comment by SOH69** [comment]
Maybe we should have a dedicated script for consumables? Or with core?

**Comment by Manason** [comment]
> Maybe we should have a dedicated script for consumables? Or with core?

It seems to me the proper place for items is in ox_inventory data/items.lua
We could maintain a snippets repo maybe for people to copy and paste items in? I'm not sure what if any logic is needed that ox_inventory wouldn't support requiring a separate repo

**Comment by SOH69** [comment]
But you still the required event that you manage consumables, in my pr you can remove the createuseable loop, in items.lua you declare the event name, and with few changes with my commit that can be used as a handler

**Comment by MafewTM** [comment]
We'll keep that in mind.

**Pull request closed without merging**
