### PR TITLE
refactor: improve consumeables logic even more

### PR DESCRIPTION
**Pull request by TonybynMp4**
## Description

Improves the consumeables logic more, 
Added config for a few things:
animation / prop,
stress relief,
sustenance,
Alcohol level (how drunk you get)

Also fixed how the random worked, setting a random value in config WILL NOT make a new value everytime..

Also changed to use client callback instead of client events, *sounds* better to me, might be wrong tho.

Needs testing, but it's way too late for me to do that lol
## Checklist

- [ ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

### CODE REVIEW

**Comment by mafewtm** [comment]
Can we just rename the stupid consumable table names? Idk why they made it ConsumablesEat and whatnot

**Comment by DevX32** [comment]
> Can we just rename the stupid consumable table names? Idk why they made it ConsumablesEat and whatnot

that would be better

**Review by BerkieBb — APPROVED** [review]

**Comment by TonybynMp4** [comment]
> Can we just rename the stupid consumable table names? Idk why they made it ConsumablesEat and whatnot

What would you rename them to 🤔

**Comment by BerkieBb** [comment]
Combine them into a consumables table and give them each a type

**Comment by TonybynMp4** [comment]
> Combine them into a consumables table and give them each a type
 
Berkie ily smart guy

**Comment by TonybynMp4** [comment]
I hate annotations.

**Review by mafewtm — APPROVED** [review]

**Pull request merged**
